version: "3.4"

networks:
  interviewer-network:
    driver: bridge

services:

  api:
    container_name: interviewer-api
    image: {api}
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 5001:5001
    networks:
      - interviewer-network
    volumes:
      - ~/.aspnet/https:/https:ro

  elasticsearch:
    container_name: interviewer-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    networks:
      - interviewer-network

  kibana:
    container_name: interviewer-kibana
    image: docker.elastic.co/kibana/kibana:8.0.0
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - interviewer-network

volumes:
  elasticsearch-data:
