using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Domain.Validation.Exceptions;
using TestUtils.Db;
using TestUtils.Fakes;
using Web.Api.Features.Companies.CreateCompany;
using Xunit;

namespace Web.Api.Tests.Features.Companies.CreateCompany;

public class CreateCompanyHandlerTests
{
    [Fact]
    public async Task Handle_ValidRequest_CompanyCreated()
    {
        await using var context = new InMemoryDatabaseContext();
        var handler = new CreateCompanyHandler(context);

        var request = new CreateCompanyBodyRequest
        {
            Name = "Test Company",
            Description = "Test Description",
            Links = new List<string> { "https://example.com" },
            LogoUrl = "https://example.com/logo.png",
        };

        context.ChangeTracker.Clear();
        var result = await handler.Handle(request, CancellationToken.None);

        Assert.NotNull(result);
        Assert.Equal("Test Company", result.Name);

        var company = context.Companies.First(x => x.Id == result.Id);
        Assert.NotNull(company);
        Assert.StartsWith("test-company-", company.Slug);
    }

    [Fact]
    public async Task Handle_WithCustomSlug_SlugUsed()
    {
        await using var context = new InMemoryDatabaseContext();
        var handler = new CreateCompanyHandler(context);

        var request = new CreateCompanyBodyRequest
        {
            Name = "Test Company",
            Description = "Test Description",
            Links = new List<string>(),
            LogoUrl = null,
            Slug = "my-custom-slug",
        };

        context.ChangeTracker.Clear();
        var result = await handler.Handle(request, CancellationToken.None);

        Assert.NotNull(result);

        var company = context.Companies.First(x => x.Id == result.Id);
        Assert.Equal("my-custom-slug", company.Slug);
    }

    [Fact]
    public async Task Handle_WithCustomSlugNeedingNormalization_SlugNormalized()
    {
        await using var context = new InMemoryDatabaseContext();
        var handler = new CreateCompanyHandler(context);

        var request = new CreateCompanyBodyRequest
        {
            Name = "Test Company",
            Description = "Test Description",
            Links = new List<string>(),
            LogoUrl = null,
            Slug = "My Custom Slug",
        };

        context.ChangeTracker.Clear();
        var result = await handler.Handle(request, CancellationToken.None);

        Assert.NotNull(result);

        var company = context.Companies.First(x => x.Id == result.Id);
        Assert.Equal("my-custom-slug", company.Slug);
    }

    [Fact]
    public async Task Handle_WithNullSlug_SlugAutoGenerated()
    {
        await using var context = new InMemoryDatabaseContext();
        var handler = new CreateCompanyHandler(context);

        var request = new CreateCompanyBodyRequest
        {
            Name = "Halyk Bank",
            Description = "Test Description",
            Links = new List<string>(),
            LogoUrl = null,
            Slug = null,
        };

        context.ChangeTracker.Clear();
        var result = await handler.Handle(request, CancellationToken.None);

        Assert.NotNull(result);

        var company = context.Companies.First(x => x.Id == result.Id);
        Assert.StartsWith("halyk-bank-", company.Slug);
    }

    [Fact]
    public async Task Handle_WithEmptySlug_SlugAutoGenerated()
    {
        await using var context = new InMemoryDatabaseContext();
        var handler = new CreateCompanyHandler(context);

        var request = new CreateCompanyBodyRequest
        {
            Name = "Halyk Bank",
            Description = "Test Description",
            Links = new List<string>(),
            LogoUrl = null,
            Slug = string.Empty,
        };

        context.ChangeTracker.Clear();
        var result = await handler.Handle(request, CancellationToken.None);

        Assert.NotNull(result);

        var company = context.Companies.First(x => x.Id == result.Id);
        Assert.StartsWith("halyk-bank-", company.Slug);
    }

    [Fact]
    public async Task Handle_DuplicateName_ThrowsBadRequest()
    {
        await using var context = new InMemoryDatabaseContext();
        new CompanyFake().Please(context);

        var handler = new CreateCompanyHandler(context);

        var request = new CreateCompanyBodyRequest
        {
            Name = "Company name",
            Description = "Another description",
            Links = new List<string>(),
            LogoUrl = null,
        };

        context.ChangeTracker.Clear();
        await Assert.ThrowsAsync<BadRequestException>(
            () => handler.Handle(request, CancellationToken.None));
    }

    [Fact]
    public async Task Handle_DuplicateSlug_ThrowsBadRequest()
    {
        await using var context = new InMemoryDatabaseContext();
        var existingCompany = new CompanyFake().Please(context);
        var existingSlug = existingCompany.Slug;

        var handler = new CreateCompanyHandler(context);

        var request = new CreateCompanyBodyRequest
        {
            Name = "Different Company Name",
            Description = "Test Description",
            Links = new List<string>(),
            LogoUrl = null,
            Slug = existingSlug,
        };

        context.ChangeTracker.Clear();
        await Assert.ThrowsAsync<BadRequestException>(
            () => handler.Handle(request, CancellationToken.None));
    }
}
