name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      solution-file: ./src/Petrel.Taxer.sln
      AUTH0_AUDIENCE: $AUTH0_AUDIENCE
      DATABASE_CONNECTION_STRING: $DATABASE_CONNECTION_STRING
      PROD_ELASTICSEARCH_LINK: $PROD_ELASTICSEARCH_LINK
      S3_ACCESS_KEY: $S3_ACCESS_KEY
      S3_ACCESS_SECRET: $S3_ACCESS_SECRET
      S3_BUCKET_NAME: $S3_BUCKET_NAME
      SENDGRID_API_KEY: $SENDGRID_API_KEY
    steps:
      - uses: actions/checkout@v2
      - name: Backend build and test
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"
      - name: Variables
        run: |
          echo ${{ env.AUTH0_AUDIENCE }}
          echo ${{ env.DATABASE_CONNECTION_STRING }}
          echo ${{ env.PROD_ELASTICSEARCH_LINK }}
          echo ${{ env.S3_ACCESS_KEY }}
          echo ${{ env.S3_ACCESS_SECRET }}
          echo ${{ env.S3_BUCKET_NAME }}
          echo ${{ env.SENDGRID_API_KEY }}
      - name: Install dependencies
        run: dotnet restore ${{env.solution-file}}
      - name: Test
        run: dotnet test ${{env.solution-file}} --no-restore --verbosity normal