name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      solution-file: ./src/techinterview.sln
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Backend build and test
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.100"
      - name: Install dependencies
        run: dotnet restore ${{env.solution-file}}
      - name: Test
        run: dotnet test ${{env.solution-file}} --no-restore --verbosity normal
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
          