name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # tests:
  #   runs-on: ubuntu-latest
  #   env:
  #     solution-file: ./src/Petrel.Taxer.sln
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Backend build and test
  #       uses: actions/setup-dotnet@v1
  #       with:
  #         dotnet-version: "6.0.x"
  #     - name: Install dependencies
  #       run: dotnet restore ${{env.solution-file}}
  #     - name: Test
  #       run: dotnet test ${{env.solution-file}} --no-restore --verbosity normal
  build:
    # needs: tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
