name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      solution-file: ./src/Petrel.Taxer.sln
    steps:
      - uses: actions/checkout@v2
      - name: Backend build and test
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"
      - name: Variables
        run: |
          echo ${{ vars.AUTH0_AUDIENCE }}
          echo ${{ vars.DATABASE_CONNECTION_STRING }}
          echo ${{ vars.PROD_ELASTICSEARCH_LINK }}
          echo ${{ vars.S3_ACCESS_KEY }}
          echo ${{ vars.S3_ACCESS_SECRET }}
          echo ${{ vars.S3_BUCKET_NAME }}
          echo ${{ vars.SENDGRID_API_KEY }}
      - name: Install dependencies
        run: dotnet restore ${{env.solution-file}}
      - name: Test
        run: dotnet test ${{env.solution-file}} --no-restore --verbosity normal